ARG GO_VERSION
FROM golang:${GO_VERSION} as build
#FROM busybox as build
COPY ./src/ /home/app/src/
# Set working directory
WORKDIR /home/app/src
RUN go build  -o /home/app/build/app ./cmd/httpserver/

FROM debian:stable-slim as run
ARG APPLICATION__ENABLE_PROFILING
ARG AUTH__SIGN_KEY
ARG RABBITMQ__USER
ARG RABBITMQ_PASSWORD
ARG RABBITMQ_HOST
ARG RABBITMQ_PORT
ARG RABBITMQ_VHOST

COPY --from=build /home/app/build/app /app
COPY --from=build /home/app/src/config.yml /config.yml
COPY --from=build /home/app/src/key/ /key/

RUN echo ${APPLICATION__ENABLE_PROFILING}
RUN echo ${AUTH__SIGN_KEY}
RUN echo ${RABBITMQ__USER}
RUN echo ${RABBITMQ_PASSWORD}
RUN echo ${RABBITMQ_HOST}
RUN echo ${RABBITMQ_PORT}
RUN echo ${RABBITMQ_VHOST}

ENV APPLICATION__ENABLE_PROFILING=${APPLICATION__ENABLE_PROFILING}
ENV AUTH__SIGN_KEY=${AUTH__SIGN_KEY}
ENV RABBITMQ__USER=${RABBITMQ__USER}
ENV RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
ENV RABBITMQ_HOST=${RABBITMQ_HOST}
ENV RABBITMQ_PORT=${RABBITMQ_PORT}
ENV RABBITMQ_VHOST=${RABBITMQ_VHOST}


ENTRYPOINT ["/app"]