ARG GO_VERSION
FROM golang:${GO_VERSION} as build
#FROM busybox as build
COPY ./src/ /home/app/src/
# Set working directory
WORKDIR /home/app/src
RUN go build  -o /home/app/build/app ./cmd/httpserver/

FROM debian:stable-slim as run
ARG APPLICATION__ENABLE_PROFILING
ARG AUTH__SIGN_KEY
ARG RABBITMQ__USER
ARG RABBITMQ_PASSWORD
ARG RABBITMQ_HOST
ARG RABBITMQ_PORT
ARG RABBITMQ_VHOST
ARG LOGGER__STORE_TO_FILE

COPY --from=build /home/app/build/app /app
COPY --from=build /home/app/src/config.yml /config.yml
COPY --from=build /home/app/src/key/ /key/

ENV MESSENGER_APPLICATION__ENABLE_PROFILING=${APPLICATION__ENABLE_PROFILING}
ENV MESSENGER_AUTH__SIGN_KEY=${AUTH__SIGN_KEY}
ENV MESSENGER_RABBITMQ__USER=${RABBITMQ__USER}
ENV MESSENGER_RABBITMQ__PASSWORD=${RABBITMQ_PASSWORD}
ENV MESSENGER_RABBITMQ__HOST=${RABBITMQ_HOST}
ENV MESSENGER_RABBITMQ__PORT=${RABBITMQ_PORT}
ENV MESSENGER_RABBITMQ__VHOST=${RABBITMQ_VHOST}
ENV MESSENGER_LOGGER__STORE_TO_FILE=${LOGGER__STORE_TO_FILE}

ENTRYPOINT ["/app"]