ARG GO_VERSION
FROM golang:${GO_VERSION} as build
#FROM busybox as build
COPY ./src/ /home/app/src/
# Set working directory
WORKDIR /home/app/src
RUN go build  -o /home/app/build/app ./cmd/httpserver/

FROM debian:stable-slim as run
ARG MESSENGER_APPLICATION_ENABLE__PROFILING
ARG MESSENGER_RABBITMQ_USER
ARG MESSENGER_RABBITMQ_PASSWORD
ARG MESSENGER_RABBITMQ_HOST
ARG MESSENGER_RABBITMQ_PORT
ARG MESSENGER_RABBITMQ_VHOST
ARG MESSENGER_LOGGER_STORE__TO__FILE

COPY --from=build /home/app/build/app /app
COPY --from=build /home/app/src/config.yml /config.yml
COPY --from=build /home/app/src/key/ /key/

ENV MESSENGER_APPLICATION_ENABLE__PROFILING=${MESSENGER_APPLICATION_ENABLE__PROFILING}
ENV MESSENGER_RABBITMQ_USER=${MESSENGER_RABBITMQ_USER}
ENV MESSENGER_RABBITMQ_PASSWORD=${MESSENGER_RABBITMQ_PASSWORD}
ENV MESSENGER_RABBITMQ_HOST=${MESSENGER_RABBITMQ_HOST}
ENV MESSENGER_RABBITMQ_PORT=${MESSENGER_RABBITMQ_PORT}
ENV MESSENGER_RABBITMQ_VHOST=${MESSENGER_RABBITMQ_VHOST}
ENV MESSENGER_LOGGER_STORE__TO__FILE=${MESSENGER_LOGGER_STORE__TO__FILE}

ENTRYPOINT ["/app"]