services:
  #Destination Service
  app:
    build:
      context: .
      dockerfile: ./go/Dockerfile
      args:
        GO_IMAGE_NAME: ${GO_IMAGE_NAME}
        GO_IMAGE_VERSION: ${GO_IMAGE_VERSION}
    image: chat-build:${GO_IMAGE_VERSION}
    entrypoint:
      - air
      - "-c"
      - /home/www/serve/docker-compose/services/go/.air.toml
    restart: always
    volumes:
      - ../../../:/home/www
    depends_on:
      - rabbitmq
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.local`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=web"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8088"
