---
type: yml
auth:
  sign_key: jwt_secret
  private_key_path: ./key/key
  public_key_path: ./key/key.pub

http_server:
  port: 8088

rabbitmq:
  user: guest
  password: guest
  host: rabbitmq
  port: 5672
  reconnect_second: 10
  vhost:

mysql:
  port: 3306
  host: db
  db_name: app_db
  username: root
  password: password

key_generator:
  key_length: 10
  id_prefix: simple_prefix
  id_postfix: simple_postfix


