---
type: yml

application:
  graceful_shutdown_timeout: 30
  profiling_port: 1234
  enable_profiling: true

auth:
  sign_key: jwt_secret
  private_key_path: ./key/key
  public_key_path: ./key/key.pub
  access_ttl_second: 86400

http_server:
  port: 8088

rabbitmq:
  user: guest
  password: guest
  host: rabbitmq
  port: 5672
  reconnect_second: 10
  channel_cleaner_timer_in_seconds: 30
  vhost:

mysql:
  port: 3306
  host: db
  db_name: app_db
  username: root
  password: password

key_generator:
  key_length: 10
  id_prefix: simple_prefix
  id_postfix: simple_postfix

logger:
  driver: zap
  level: debug
  filepath: ./logs/log.json
  local_time: false
  max_backups: 10
  max_size: 10
  max_ager: 30



