name: CD

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches: [main]
  push:
    branches: [main]

jobs:
  cd:
    runs-on: ubuntu-latest
    needs:
      - ci
      - pr-lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install dependencies
        run: cd src && go mod tidy

      - name: build
        run: make build

      - name: deploy
        run: make deploy
