name: CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Install dependencies
        run: cd src && go mod tidy

      - name: dockerUp
        run: sudo docker-compose up -d

      - name: Test
        run: make test

      - name: dockerDown
        run: sudo docker-compose down

      - name: Format
        run: make format

      - name: Lint
        run: make lint