name: CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches: [main]
  push:
    branches: [main]

jobs:
  #  test:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v4
  #      - name: Setup Go
  #        uses: actions/setup-go@v4
  #        with:
  #          go-version: 1.22
  #      - name: Install dependencies
  #        run: cd src && go mod tidy
  #
  #      - name: dockerUp
  #        run: sudo docker-compose -f ./serve/ci_cd/docker-compose.yml up -d
  #
  #      - name: Test
  #        run: make test
  #
  #      - name: dockerDown
  #        run: sudo docker-compose -f ./serve/ci_cd/docker-compose.yml down
  #  format:
  #    needs:
  #      - test
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v4
  #      - name: Setup Go
  #        uses: actions/setup-go@v4
  #        with:
  #          go-version: 1.22
  #      - name: Format
  #        run: make format
  #
  #      - name: Lint
  #        run: make lint

  cd:
    runs-on: ubuntu-latest
    environment: production
    #    needs:
    #      - test
    #      - format
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
          node-version: 18

      - name: build
        run: make build
        env:
          DOCKER_HUB_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}
          DOCKER_HUB_USERNAME: ${{vars.DOCKER_HUB_USERNAME}}
          IMAGE_NAME: ${{vars.IMAGE_NAME}}
          IMAGE_VERSION: ${{vars.IMAGE_VERSION}}
          GITHUB_RUN_ID: ${{github.run.id}}

      - name: deploy
        run: make deploy
        env:
          LIARA_API_TOKEN: ${{secret.LIARA_API_TOKEN}}
          LIARA_USERNAME: ${{secret.LIARA_USERNAME}}