name: CI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches: [main]
  push:
    branches: [main]

jobs:
  #  test:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v4
  #      - name: Setup Go
  #        uses: actions/setup-go@v4
  #        with:
  #          go-version: 1.22
  #      - name: Install dependencies
  #        run: cd src && go mod tidy
  #
  #      - name: dockerUp
  #        run: sudo docker-compose -f ./serve/ci_cd/docker-compose.yml up -d
  #
  #      - name: Test
  #        run: make test
  #
  #      - name: dockerDown
  #        run: sudo docker-compose -f ./serve/ci_cd/docker-compose.yml down
  #  format:
  #    needs:
  #      - test
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v4
  #      - name: Setup Go
  #        uses: actions/setup-go@v4
  #        with:
  #          go-version: 1.22
  #      - name: Format
  #        run: make format
  #
  #      - name: Lint
  #        run: make lint

  cd:
    runs-on: ubuntu-latest
    environment: production
    #    needs:
    #      - test
    #      - format
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
          node-version: 18

      - name: build
        run: make build
        env:
          GO_VERSION: ${{vars.GO_VERSION}}
          DOCKER_HUB_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}
          DOCKER_HUB_USERNAME: ${{vars.DOCKER_HUB_USERNAME}}
          IMAGE_NAME: ${{vars.IMAGE_NAME}}
          IMAGE_VERSION: ${{vars.IMAGE_VERSION}}
          GITHUB_RUN_ID: ${{github.run.id}}

          MESSENGER_APPLICATION__ENABLE_PROFILING: ${{vars.MESSENGER_APPLICATION_ENABLE__PROFILING}}
          MESSENGER_LOGGER__STORE_TO_FILE: ${{vars.MESSENGER_LOGGER_STORE__TO__FILE}}
          MESSENGER_AUTH__SIGN_KEY: ${{secrets.MESSENGER_AUTH_SIGN__KEY}}
          MESSENGER_RABBITMQ__USER: ${{secrets.MESSENGER_RABBITMQ_USER}}
          MESSENGER_RABBITMQ_PASSWORD: ${{secrets.MESSENGER_RABBITMQ_PASSWORD}}
          MESSENGER_RABBITMQ_HOST: ${{secrets.MESSENGER_RABBITMQ_HOST}}
          MESSENGER_RABBITMQ_PORT: ${{secrets.MESSENGER_RABBITMQ_PORT}}
          MESSENGER_RABBITMQ_VHOST: ${{secrets.MESSENGER_RABBITMQ_VHOST}}

      - name: deploy
        run: make deploy
        env:
          IMAGE_NAME: ${{vars.IMAGE_NAME}}
          IMAGE_VERSION: ${{vars.IMAGE_VERSION}}
          LIARA_API_TOKEN: ${{secrets.LIARA_API_TOKEN}}
          APP_NAME: ${{vars.APP_NAME}}
          APP_PORT: ${{vars.APP_PORT}}
          GITHUB_RUN_ID: ${{github.run.id}}